name: AWG Daily Update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install deps
        run: pip install -r awg-config-generator/requirements.txt

      - name: 🚀 Run generator
        run: python awg-config-generator/awg_generator.py

      - name: 💾 Commit & push
        run: |
          git config --global user.name "awg-bot"
          git config --global user.email "bot@users.noreply.github.com"

          git add -A
          git commit -m "awg auto update" || echo "no changes"
          git push
