name: Update VLESS & Clash

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- FILTER ----------
      - name: Filter VLESS
        run: |
          echo "Downloading sources..."

          curl -L -o src1.txt https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt
          curl -L -o src2.txt https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt
          curl -L -o src3.txt https://raw.githubusercontent.com/vsevjik/OBSpiskov/refs/heads/main/wwh_old

          cat src1.txt src2.txt src3.txt > all.txt

          grep "^vless://" all.txt > filtered_vless.txt

          if [ ! -s filtered_vless.txt ]; then
            echo "No VLESS links found"
            exit 1
          fi

      # ---------- INSTALL SUBCONVERTER ----------
      - name: Install subconverter
        run: |
          git clone https://github.com/tindy2013/subconverter.git
          cd subconverter
          chmod +x subconverter

      # ---------- GENERATE CLASH ----------
      - name: Generate Clash YAML
        run: |
          base64 filtered_vless.txt > encoded.txt
          BASE=$(cat encoded.txt | tr -d '\n')

          ./subconverter/subconverter \
            -g \
            -u "$BASE" \
            -t clash \
            -o clash_pool.yaml

      # ---------- VALIDATE ----------
      - name: Validate YAML
        run: |
          if [ -s clash_pool.yaml ]; then
            echo "YAML generated successfully"
          else
            echo "Empty YAML generated"
            exit 1
          fi

      # ---------- COMMIT ----------
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add filtered_vless.txt clash_pool.yaml
          git commit -m "Auto update VLESS & Clash" || echo "No changes"
          git push
