name: Auto Update VLESS & Clash

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # каждые 30 минут

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Run filter script
        run: pwsh ./filter.ps1

      - name: Generate Clash config
        run: pwsh ./generate_clash.ps1

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update subscription"
          git push
